version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: eventengage_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: eventuser
      POSTGRES_PASSWORD: eventpass
      POSTGRES_DB: eventengage
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: